keepEmptyPriority: true
code:
  include_lists:
    - TODO
    - DOING
    - DONE
    - PLANNING
    - FIXME
    - ARCHIVE
    - HACK
    - CHANGED
    - XXX
    - IDEA
    - NOTE
    - REVIEW
    - CURRENT
    - BACKLOG
lists:
  - hidden: false
    ignore: false
    name: NOTE
    id: jea6phpllxpsj7m
  - name: BACKLOG
    hidden: false
    ignore: false
    id: jea67colm3nm22s
  - hidden: false
    name: TODO
    id: jea6phpllxpsj7j
  - hidden: false
    name: DOING
    id: jea6phpllxpsj7k
  - hidden: false
    ignore: false
    name: DONE
    id: jea6phpllxpsj7l
settings:
  openIn: default
  customOpenIn: ''
  editorTheme: blackboard
  journalType: New File
  journalPath: stories
  appendNewCardsTo: imdone-tasks.md
  newCardSyntax: HASHTAG
  replaceSpacesWith: '-'
  plugins:
    devMode: false
  journalTemplate: null
  theme: dark
  views: []
  name: backlog
  cards:
    colors: []
    template: |

      <!-- created:${(new Date()).toISOString()} task-id:${sid} -->
    trackChanges: false
    metaNewLine: false
    addCompletedMeta: false
    addCheckBoxTasks: false
    doneList: DONE
    taskPrefix: '##'
    tagPrefix: +
    metaSep: ':'
    orderMeta: true
    maxLines: 6
    addNewCardsToTop: true
    defaultList: TODO
