keepEmptyPriority: true
code:
  include_lists:
    - TODO
    - DOING
    - DONE
    - PLANNING
    - FIXME
    - ARCHIVE
    - HACK
    - CHANGED
    - XXX
    - IDEA
    - NOTE
    - REVIEW
    - CURRENT
    - BACKLOG
lists:
  - name: BACKLOG
    hidden: true
    ignore: false
    id: jea67colm3nm22s
  - name: TODO
    hidden: false
    ignore: false
    id: jea6phpllxpsj7j
  - name: DOING
    hidden: false
    ignore: false
    id: jea6phpllxpsj7k
  - name: DONE
    hidden: false
    ignore: false
    id: jea6phpllxpsj7l
settings:
  openIn: default
  customOpenIn: ''
  editorTheme: blackboard
  journalType: New File
  journalPath: stories
  appendNewCardsTo: imdone-tasks.md
  newCardSyntax: HASHTAG
  replaceSpacesWith: '-'
  plugins:
    devMode: false
    CliBacklogPlugin:
      projectType: BACKLOG_PROJECT
      storyTemplate: |
        # Story id

        As a <role>, I want <feature>, so that <benefit>.

        ## Acceptance Criteria

        - [ ] Criteria 1
        - [ ] Criteria 2

        ## Tasks

        ### Phase One Tasks

        - [ ] Task 1

        ### DoD

        - [ ] Acceptance criteria are met
        - [ ] Refactoring is complete
        - [ ] Code builds with no error
        - [ ] Unit tests are written and pass
        - [ ] Existing Unit Tests pass
        - [ ] Sufficient diagnostics/telemetry are logged
        - [ ] Code review is complete
        - [ ] UX review is complete (if applicable)
        - [ ] Documentation is updated
        - [ ] The feature is merged into the develop branch
        - [ ] The feature is signed off by the product owner
  journalTemplate: ''
  theme: dark
  views: []
  name: backlog
  cards:
    colors: []
    template: |

      <!--
      #story
      created:${(new Date()).toISOString()}
      task-id:${sid}
      -->
    trackChanges: false
    metaNewLine: true
    addCompletedMeta: true
    addCheckBoxTasks: false
    doneList: DONE
    taskPrefix: '##'
    tagPrefix: '#'
    metaSep: ':'
    orderMeta: true
    maxLines: 6
    addNewCardsToTop: true
    defaultList: TODO
  defaultFilter: allTags = "story"
