'use strict';

var cBlock = {"start":"/*", "end":"*/", "ignore":"*"};
module.exports = { 
  ".coffee":      {"name": "coffeescript", "symbol": "#"},
  ".litcoffee":   {"name": "coffeescript", "symbol": "#", "literate": true},
  "Cakefile":     {"name": "coffeescript", "symbol": "#"},
  ".rb":          {"name": "ruby", "symbol": "#"},
  ".py":          {"name": "python", "symbol": "#"},
  ".tex":         {"name": "tex", "symbol": "%"},
  ".latex":       {"name": "tex", "symbol": "%"},
  ".js":          {"name": "javascript", "symbol": "//", "block": cBlock},
  ".java":        {"name": "java", "symbol": "//", "block": cBlock},
  ".scss":        {"name": "scss", "symbol": "//"},
  ".cpp":         {"name": "cpp", "symbol": "//", "block": cBlock},
  ".cc":          {"name": "cpp", "symbol": "//", "block": cBlock},
  ".php":         {"name": "php", "symbol": "//"},
  ".hs":          {"name": "haskell", "symbol": "--"},
  ".erl":         {"name": "erlang", "symbol": "%"},
  ".hrl":         {"name": "erlang", "symbol": "%"},
  ".md":          {"name": "markdown", "symbol": ""},
  ".markdown":    {"name": "markdown", "symbol": ""},
  ".less":        {"name": "scss", "symbol": "//"},
  ".c":           {"name": "c", "symbol":"//", "block": cBlock},
  ".h":           {"name": "objectivec", "symbol": "//", "block": cBlock},
  ".m":           {"name": "objectivec", "symbol": "//", "block": cBlock},
  ".mm":          {"name": "objectivec", "symbol": "//", "block": cBlock},
  ".m4":          {"name": "m4", "symbol": "#"},
  ".scala":       {"name": "scala", "symbol": "//"},
  ".cs":          {"name": "cs", "symbol": "//"},
  ".as":          {"name": "actionscript", "symbol": "//"},
  ".scpt":        {"name": "applescript", "symbol": "--"},
  ".applescript": {"name": "applescript", "symbol": "--"},
  ".sh":          {"name": "bash", "symbol": "#"},
  ".clj":         {"name": "clojure", "symbol": ";"},
  ".cmake":       {"name": "cmake", "symbol": "#"},
  ".d":           {"name": "d", "symbol": "//"},
  ".p":           {"name": "delphi", "symbol": "//"},
  ".pp":          {"name": "delphi", "symbol": "//"},
  ".pas":         {"name": "delphi", "symbol": "//"},
  ".bat":         {"name": "dos", "symbol": "@?rem"},
  ".btm":         {"name": "dos", "symbol": "@?rem"},
  ".cmd":         {"name": "dos", "symbol": "@?rem"},
  ".go":          {"name": "go", "symbol": "//", "block": cBlock},
  ".ini":         {"name": "ini", "symbol": ";"},
  ".lisp":        {"name": "lisp", "symbol": ";"},
  ".mel":         {"name": "mel", "symbol": "//"},
  ".pl":          {"name": "perl", "symbol": "#"},
  ".pm":          {"name": "perl", "symbol": "#"},
  ".pod":         {"name": "perl", "symbol": "#"},
  ".t":           {"name": "perl", "symbol": "#"},
  ".r":           {"name": "r", "symbol": "#"},
  ".rc":          {"name": "rust", "symbol": "//"},
  ".rs":          {"name": "rust", "symbol": "//"},
  ".sql":         {"name": "sql", "symbol": "--"},
  ".vala":        {"name": "vala", "symbol": "//"},
  ".vapi":        {"name": "vala", "symbol": "//"},
  ".vbe":         {"name": "vbscript", "symbol": "'"},
  ".vbs":         {"name": "vbscript", "symbol": "'"},
  ".wsc":         {"name": "vbscript", "symbol": "'"},
  ".wsf":         {"name": "vbscript", "symbol": "'"},
  ".vhdl":        {"name": "vhdl", "symbol": "--"},
  ".bas":         {"name": "basic", "symbol": "REM"}
};
