keepEmptyPriority: false
code:
  include_lists:
    - TODO
    - DOING
    - DONE
    - PLANNING
    - FIXME
    - ARCHIVE
    - HACK
    - CHANGED
    - XXX
    - IDEA
    - NOTE
    - REVIEW
    - BACKLOG
    - READY
lists:
  - hidden: true
    name: FIXME
  - hidden: false
    name: BACKLOG
  - hidden: false
    name: TODO
  - hidden: false
    name: DOING
  - hidden: false
    name: READY
  - hidden: false
    ignore: true
    name: DONE
marked:
  gfm: true
  tables: true
  breaks: false
  pedantic: false
  smartLists: true
  langPrefix: language-
settings:
  journalType: Folder
  journalPath: /notes
  taskPrefix: '#'
  maxLines: 4
  addNewCardsToTop: true
  newCardSyntax: MARKDOWN
  cards:
    colors:
      - color: green
        filter: 'contains(allTags,story)'
      - color: black
        filter: list=TODO
      - color: red
        filter: allTags=contains=urgent
      - color: red
        filter: ':bug:'
  doneList: DONE
  filteredLists: []
