code:
  include_lists:
    - TODO
    - DOING
    - DONE
    - PLANNING
    - FIXME
    - ARCHIVE
    - HACK
    - CHANGED
    - XXX
    - IDEA
    - NOTE
    - REVIEW
    - BACKLOG
    - READY
    - ABANDONED
lists:
  - name: FIXME
    hidden: false
    ignore: false
    id: sktwi22bvlvppcr50
  - name: NOTE
    hidden: true
    ignore: false
    id: jea6nx7llx85j9k
  - name: HACK
    hidden: true
    ignore: false
    id: jea6nx7llx85j9l
  - name: BACKLOG
    hidden: true
    ignore: false
    id: jea6nx7llx85j9m
  - name: TODO
    hidden: false
    ignore: false
    id: jea6nx7llx85j9n
  - name: DOING
    hidden: false
    ignore: false
    id: jea6nx7llx85j9o
  - name: READY
    hidden: false
    ignore: false
    id: jea6nx7llx85j9p
  - name: DONE
    hidden: false
    ignore: true
    id: jea6nx7llx85j9q
  - name: ABANDONED
    hidden: true
    ignore: true
    id: jea6b3hlxv87stb
settings:
  openIn: code
  journalType: Folder
  journalPath: notes
  appendNewCardsTo: imdone-tasks.md
  newCardSyntax: MARKDOWN
  replaceSpacesWith: '-'
  plugins:
    devMode: false
    imdone-sample-plugin:
      tags: []
      meta:
        - key: expand
          value: '1'
        - key: epic
          value: Release 1.29.0
        - key: epic
          value: Release 2.0
  journalTemplate: null
  markdownOnly: false
  theme: dark
  editorTheme: blackboard
  filteredLists: []
  filterHistory:
    - allMeta.id = "4"
  views: []
  name: imdone core
  defaultFilter: !<tag:yaml.org,2002:js/undefined> ''
  cards:
    colors:
      - color: green
        filter: 'contains(allTags,story)'
      - color: black
        filter: list=TODO
      - color: red
        filter: allTags=contains=urgent
      - color: red
        filter: ':bug:'
      - color: green
        filter: list=DOING
    template: |

      <!--
      created:${(new Date()).toISOString()}
      -->
    trackChanges: false
    metaNewLine: true
    addCompletedMeta: true
    addCheckBoxTasks: false
    doneList: DONE
    taskPrefix: '#'
    tagPrefix: '#'
    metaSep: ':'
    orderMeta: true
    maxLines: 4
    addNewCardsToTop: true
    showTagsAndMeta: true
    links:
      - href: >-
          https://twitter.com/intent/tweet?text=${encodedText}%0ATweeted%20with%20@imdoneio
        icon: twitter
        pack: fab
        title: Tweet this card
    defaultList: FIXME
