keepEmptyPriority: false
code:
  include_lists:
    - TODO
    - DOING
    - DONE
    - PLANNING
    - FIXME
    - ARCHIVE
    - HACK
    - CHANGED
    - XXX
    - IDEA
    - NOTE
    - REVIEW
    - BACKLOG
    - READY
lists:
  - hidden: true
    name: FIXME
  - hidden: false
    name: BACKLOG
  - hidden: false
    name: TODO
  - hidden: false
    name: DOING
  - hidden: false
    name: READY
  - hidden: false
    ignore: true
    name: DONE
marked:
  gfm: true
  tables: true
  breaks: false
  pedantic: false
  smartLists: true
  langPrefix: language-
settings:
  journalType: Folder
  journalPath: /notes
  taskPrefix: '#'
  maxLines: 4
  addNewCardsToTop: true
  newCardSyntax: MARKDOWN
  cards:
    colors:
      - color: green
        filter: 'contains(allTags,story)'
      - color: black
        filter: list=TODO
      - color: red
        filter: allTags=contains=urgent
      - color: red
        filter: ':bug:'
    addCompletedMeta: true
  doneList: DONE
  filterHistory:
    - allMeta.id = "4"
  filteredLists: []
  journalTemplate: |
    ---
    computed:
      date: (new Date()).toDateString()
      time: (new Date()).toLocaleTimeString()
      timestamp: (new Date()).toISOString()
    template: | # This is the template for new cards that are created in imdone
      
      <!-- created:${timestamp} -->
      <!--[[{{source.path}}:{{line}}]({{source.path}}:{{line}}) ]-->
      <!-- expand:1 -->
    links:
      - pack: fab # Can be fab or fas https://fontawesome.com/how-to-use/on-the-web/referencing-icons/basic-use
        icon: fa-twitter # The font-awesome icon to use
        title: Tweet this card
        href: https://twitter.com/intent/tweet?text=${encodedText}%0ATweeted%20with%20@imdoneio
    ---
      
  tagPrefix: '#'
  openIn: code
  defaultList: FIXME
