keepEmptyPriority: true
code:
  include_lists:
    - TODO
    - DOING
    - DONE
    - PLANNING
    - FIXME
    - ARCHIVE
    - HACK
    - CHANGED
    - XXX
    - IDEA
    - NOTE
    - REVIEW
    - BACKLOG
    - READY
    - ABANDONED
lists:
  - name: NOTE
    hidden: false
    ignore: false
    id: jea6nx7llx85j9k
  - name: FIXME
    hidden: true
    ignore: false
    id: sktwi22bvlvppcr50
  - name: Past Due Reminders
    hidden: true
    ignore: false
    id: jea613h4lzjqljbo
    filter: 'remind = /./ and remind < "${now}" and list != READY and list != DONE'
  - name: HACK
    hidden: true
    ignore: false
    id: jea6nx7llx85j9l
  - name: BACKLOG
    hidden: false
    ignore: false
    id: jea6nx7llx85j9m
  - name: TODO
    hidden: false
    ignore: false
    id: jea6nx7llx85j9n
  - name: DOING
    hidden: false
    ignore: false
    id: jea6nx7llx85j9o
  - name: READY
    hidden: false
    ignore: false
    id: jea6nx7llx85j9p
  - name: DONE
    hidden: false
    ignore: true
    id: jea6nx7llx85j9q
  - name: ABANDONED
    hidden: true
    ignore: true
    id: jea6b3hlxv87stb
settings:
  openIn: code
  openCodeIn: default
  journalType: New File
  journalPath: notes
  appendNewCardsTo: imdone-tasks.md
  newCardSyntax: HASHTAG
  replaceSpacesWith: '-'
  plugins:
    imdone-sample-plugin:
      tags: []
      meta:
        - key: expand
          value: '1'
        - key: epic
          value: Release 1.29.0
        - key: epic
          value: Release 2.0
    SamplePlugin:
      tags: []
      meta: []
    HeaderFooterPlugin:
      afterPrefix: '${!/.md$/.test(relPath) ? ''## **:hammer_and_wrench:** '' : ''''}'
    devMode: false
  journalTemplate: null
  markdownOnly: false
  theme: dark
  editorTheme: blackboard
  filterHistory:
    - allMeta.id = "4"
  views: []
  name: "\U0001F3AF imdone core"
  defaultFilter: !<tag:yaml.org,2002:js/undefined> ''
  kudosProbability: 0.33
  cards:
    colors:
      - color: green
        filter: 'contains(allTags,story)'
      - color: black
        filter: list=TODO
      - color: red
        filter: allTags=contains=urgent
      - color: red
        filter: ':bug:'
      - color: green
        filter: list=DOING
    template: |

      <!--
      created:${(new Date()).toISOString()}
      -->
    trackChanges: false
    metaNewLine: true
    addCompletedMeta: true
    addCheckBoxTasks: false
    doingList: DOING
    doneList: DONE
    tokenPrefix: '#'
    taskPrefix: '#'
    tagPrefix: '#'
    metaSep: ':'
    orderMeta: true
    maxLines: 4
    addNewCardsToTop: true
    showTagsAndMeta: false
    links:
      - href: >-
          https://twitter.com/intent/tweet?text=${encodedText}%0ATweeted%20with%20@imdoneio
        icon: twitter
        pack: fab
        title: Tweet this card
    defaultList: FIXME
    archiveCompleted: true
    archiveFolder: notes/archive
