keepEmptyPriority: false
code:
  include_lists:
    - TODO
    - DOING
    - DONE
    - PLANNING
    - FIXME
    - ARCHIVE
    - HACK
    - CHANGED
    - XXX
    - IDEA
    - NOTE
    - REVIEW
    - BACKLOG
    - READY
lists:
  - hidden: true
    name: FIXME
  - name: NOTE
    hidden: false
    ignore: false
  - name: HACK
    hidden: true
    ignore: false
  - hidden: false
    name: BACKLOG
  - hidden: false
    name: TODO
  - hidden: false
    name: DOING
  - hidden: false
    name: READY
  - hidden: false
    ignore: true
    name: DONE
marked:
  gfm: true
  tables: true
  breaks: false
  pedantic: false
  smartLists: true
  langPrefix: language-
settings:
  openIn: code
  customOpenIn: ''
  editorTheme: blackboard
  journalType: Folder
  journalPath: notes
  appendNewCardsTo: imdone-tasks.md
  newCardSyntax: MARKDOWN
  replaceSpacesWith: '-'
  plugins:
    devMode: false
    imdone-sample-plugin:
      tags: []
      meta:
        - key: expand
          value: '1'
        - key: epic
          value: Release 1.29.0
        - key: epic
          value: Release 2.0
  filteredLists: []
  journalTemplate: null
  theme: dark
  filterHistory:
    - allMeta.id = "4"
  views:
    - id: default
      defaultFilter: ''
  name: imdone core
  cards:
    colors:
      - color: green
        filter: 'contains(allTags,story)'
      - color: black
        filter: list=TODO
      - color: red
        filter: allTags=contains=urgent
      - color: red
        filter: ':bug:'
    template: |

      <!--
      created:${(new Date()).toISOString()}
      -->
    trackChanges: false
    metaNewLine: false
    addCompletedMeta: true
    addCheckBoxTasks: false
    doneList: DONE
    taskPrefix: '#'
    tagPrefix: '#'
    metaSep: ':'
    maxLines: 4
    addNewCardsToTop: true
    links:
      - href: >-
          https://twitter.com/intent/tweet?text=${encodedText}%0ATweeted%20with%20@imdoneio
        icon: twitter
        pack: fab
        title: Tweet this card
    defaultList: FIXME
