keepEmptyPriority: true
code:
  include_lists:
    - TODO
    - DOING
    - DONE
    - PLANNING
    - FIXME
    - ARCHIVE
    - HACK
    - CHANGED
    - XXX
    - IDEA
    - NOTE
    - REVIEW
    - CURRENT
    - BACKLOG
lists:
  - name: TODO
    hidden: false
    ignore: false
    id: jea6phpllxpsj7j
  - name: DOING
    hidden: false
    ignore: false
    id: jea6phpllxpsj7k
  - name: DONE
    hidden: false
    ignore: false
    id: jea6phpllxpsj7l
settings:
  openIn: default
  editorTheme: blackboard
  journalType: New File
  journalPath: tasks
  appendNewCardsTo: imdone-tasks.md
  newCardSyntax: HASHTAG
  replaceSpacesWith: '-'
  plugins:
    devMode: false
    CliBacklogPlugin:
      projectType: STORY_PROJECT
      defaultBranch: !<tag:yaml.org,2002:js/undefined> ''
      remote: !<tag:yaml.org,2002:js/undefined> ''
  journalTemplate: null
  theme: dark
  markdownOnly: false
  customOpenIn: ''
  views: []
  name: Plan-should-be-able-to-add-tasks-to-an-existing-story tasks
  defaultFilter: allTags = "task"
  cards:
    colors: []
    template: |

      <!-- 
      #task
      created:${(new Date()).toISOString()}
      group:"${ungroupedTasks}"
      story-id:${projectName}
      task-id:${sid}
      -->
    trackChanges: false
    metaNewLine: true
    addCompletedMeta: true
    addCheckBoxTasks: false
    doneList: DONE
    taskPrefix: '##'
    tagPrefix: '#'
    metaSep: ':'
    orderMeta: true
    maxLines: 6
    addNewCardsToTop: true
    defaultList: TODO
